#include<stdio.h>
#include<math.h>

//TO DO
/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? */

int numOfDiv(int num);

int main(void)
{
	int sum = 0;
	int div = 0;
	int num = 1;
	
	while (div < 500)
	{
		sum += num;
		div = numOfDiv(sum);
		num++;
	}
	printf("%i ", sum);
}

int numOfDiv(int num)
{
	int div = 0;
	int sqNum = sqrt((double)num) + 1;
	
	for(int i = 2; i < sqNum; i++)
	{
		if (num % i == 0)
		{
			div++;
		}
	}
	
	div = (div * 2) + 2;
	return div;
}
