#include<stdio.h>
#include<math.h>


//TO DO
/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

int main(void)
{
	long int num = 2, temp = 1, answer = 2; //addition of all even turms
	
	while (num < 4000000)
	{
		num += temp;
		if (num % 2 == 0)
		{
			answer += num;
		}
		temp = num - temp;
	}
	
	printf("%i", answer);
}
